data_dir: "/home/r1lite/GalaxeaDataset/20260105"
max_queue_size: 5
max_age: 0.5
collection_frequency: 50

datasets:
  # "/subtask":
  #   topic: "/pedal_status"
  #   processor: "data_collector.data_processor.PedalProcessor"
  #   processor_config:
  #     output_shape: [1]
  #     dtype: "int32"
  #     description: "Pedal status converted to subtask ID: step=10, double step=100, normal=0"

  "/observations/images/cam_left_wrist":
    topic: "/hdas/camera_wrist_left/color/image_rect_raw"
    processor: "data_collector.data_processor.UniversalImageProcessor"
    processor_config:
      resize: [640, 480]
      output_shape: [480, 640, 3]
      dtype: "uint8"
      description: "Left wrist camera image"

  "/observations/images/cam_right_wrist":
    topic: "/hdas/camera_wrist_right/color/image_rect_raw"
    processor: "data_collector.data_processor.UniversalImageProcessor"
    processor_config:
      resize: [640, 480]
      output_shape: [480, 640, 3]
      dtype: "uint8"
      description: "Right wrist camera image"

  "/observations/images/cam_left_head":
    topic: "/hdas/camera_head/left_raw/image_raw_color/compressed"
    processor: "data_collector.data_processor.UniversalImageProcessor"
    processor_config:
      resize: [640, 480]
      output_shape: [480, 640, 3]
      dtype: "uint8"
      description: "Left head camera image"

  "/observations/images/cam_right_head":
    topic: "/hdas/camera_head/right_raw/image_raw_color/compressed"
    processor: "data_collector.data_processor.UniversalImageProcessor"
    processor_config:
      resize: [640, 480]
      output_shape: [480, 640, 3]
      dtype: "uint8"
      description: "Right head camera image"

  "/state/joint_position/left":
    topic: "/hdas/feedback_arm_left"
    processor: "data_collector.data_processor.R1LiteJointPositionProcessor"
    processor_config:
      output_shape: [7]
      dtype: "float64"
      description: "Left arm joint positions"

  "/state/joint_position/right":
    topic: "/hdas/feedback_arm_right"
    processor: "data_collector.data_processor.R1LiteJointPositionProcessor"
    processor_config:
      output_shape: [7]
      dtype: "float64"
      description: "Right arm joint positions"


topics:
  # "/pedal_status":
  #   msg_type: "sensor_msgs.msg.Joy"
  #   description: "Pedal input device"

  "/hdas/camera_wrist_left/color/image_rect_raw":
    msg_type: "sensor_msgs.msg.Image"
    description: "Left wrist camera"

  "/hdas/camera_wrist_right/color/image_rect_raw":
    msg_type: "sensor_msgs.msg.Image"
    description: "Right wrist camera"

  "/hdas/camera_head/left_raw/image_raw_color/compressed":
    msg_type: "sensor_msgs.msg.CompressedImage"
    description: "Left head camera"

  "/hdas/camera_head/right_raw/image_raw_color/compressed":
    msg_type: "sensor_msgs.msg.CompressedImage"
    description: "Right head camera"

  "/hdas/feedback_arm_left":
    msg_type: "sensor_msgs.msg.JointState"
    description: "Left arm status"

  "/hdas/feedback_arm_right":
    msg_type: "sensor_msgs.msg.JointState"
    description: "Right arm status"